RUNTIME_VERSION = "1.0.0"
API_VERSION = "1.0"
SCHEMA_VERSION = "1.0"
RECORD_SCHEMA_VERSION = "1.0"
PROJECTION_VERSION = 1
TRIAL_KEY_VERSION = "trial-key-1"
FTS_TOKENIZER = "unicode61 remove_diacritics 2"
