#!/usr/bin/env python3
"""Assemble the stdlib-only single-file artifacts (§11).

* ``build/fq-node`` = ``fleetq/bundles.py`` + ``fleetq/shim/fq_node.py``
* ``bin/fq``        = ``fleetq/bundles.py`` + ``fleetq/client.py``

The build is reproducible: the same sources give byte-identical output, and
each artifact records a digest of its inputs, so a node or client can report
exactly which code it runs. ``--check`` fails if a committed artifact is stale.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "fleetq"

ARTIFACTS = {
    ROOT / "build" / "fq-node": [SRC / "bundles.py", SRC / "shim" / "fq_node.py"],
    ROOT / "bin" / "fq": [SRC / "bundles.py", SRC / "client.py"],
}


def _strip(text: str) -> str:
    out = []
    for line in text.splitlines():
        if line.strip() == "from __future__ import annotations":
            continue
        out.append(line)
    return "\n".join(out) + "\n"


def assemble(parts: list[Path]) -> str:
    body = "".join(f"\n# ---- {p.relative_to(ROOT)} " + "-" * 40 + "\n" + _strip(p.read_text()) for p in parts)
    digest = hashlib.sha256(body.encode()).hexdigest()[:16]
    return (
        "#!/usr/bin/env python3\n"
        f"# Generated by scripts/build.py from {', '.join(str(p.relative_to(ROOT)) for p in parts)}.\n"
        "# Do not edit; edit the sources and rebuild.\n"
        "from __future__ import annotations\n"
        f"BUILD_DIGEST = {digest!r}\n"
        + body
        + "\nif __name__ == '__main__':\n    import sys as _sys\n    _sys.exit(main())\n"
    )


def main(argv: list[str]) -> int:
    check = "--check" in argv
    stale = []
    for target, parts in ARTIFACTS.items():
        if not all(p.exists() for p in parts):
            continue
        text = assemble(parts)
        if check:
            if not target.exists() or target.read_text() != text:
                stale.append(str(target.relative_to(ROOT)))
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text)
        target.chmod(0o755)
        print(f"built {target.relative_to(ROOT)}")
    if stale:
        print("stale artifacts (run scripts/build.py): " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
